name: gogo_mvp
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.2.2+22

environment:
  sdk: '>=3.0.2 <4.0.0'
dependencies:

  flutter:
    sdk: flutter

  # module
  gogo_mvp_domain:
    path: ./domain
  gogo_mvp_data:
    path: ./data

  # Service Locator
  get_it: ^7.6.0

  # UI
  intl: ^0.18.0
  view_model_kit: ^0.2.2
  flutter_svg: ^2.0.7
  flutter_animate: ^4.2.0+1
  cached_network_image: ^3.2.3
  animated_text_kit: ^4.2.2
  linkfy_text:
    git:
      url: https://github.com/note11g/linkfy_text.git
      ref: 38ac64c8615fc018ccfeebcf9cad23d70f289609
  flutter_styled_toast_plus:
    git: https://github.com/note11g/flutter_styled_toast.git
  photo_view: ^0.14.0

  # Router
  go_router: ^10.0.0

  # firebase
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.3.4
  firebase_messaging: ^14.6.5
  firebase_dynamic_links: ^5.3.4

  # oAuth login
  kakao_flutter_sdk_user: ^1.5.0
  sign_in_with_apple: ^5.0.0

  # amplitude
  amplitude_flutter: ^3.16.0

  # native util
  image_picker: ^1.0.1
  url_launcher: ^6.1.12
  flutter_image_compress: ^2.0.4
  path_provider: ^2.0.15
  package_info_plus: ^4.0.2
  flutter_local_notifications: ^15.1.0+1
  crypto: ^3.0.3
  image_gallery_saver: ^2.0.3
  share_plus: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.1

flutter:
  uses-material-design: true

  fonts:
    - family: NanumSquareNeo
      fonts:
        - asset: assets/fonts/NanumSquareNeo-Variable.ttf
    - family: Pretendard
      fonts:
        - asset: assets/fonts/PretendardVariable.ttf

  assets:
    - assets/images/
    - assets/icons/
